import { prisma } from '@civiq/db';

export interface AuditLogEntry {
  action: string;
  objectType?: string;
  objectId?: string;
  jurisdictionId?: string;
  requestId?: string;
  payload?: Record<string, any>;
  ipAddress?: string;
  userAgent?: string;
}

const SECRET_KEYS = ['password', 'token', 'aadhaar', 'pan', 'secret', 'key'];

export class AuditService {
  /**
   * Helper to strip secrets from payload before writing to the DB
   */
  public stripSecrets(payload?: Record<string, any>): Record<string, any> {
    if (!payload) return {};
    const safePayload = { ...payload };
    
    for (const key of Object.keys(safePayload)) {
      if (SECRET_KEYS.some((secretKey) => key.toLowerCase().includes(secretKey))) {
        safePayload[key] = '[REDACTED]';
      } else if (typeof safePayload[key] === 'object' && safePayload[key] !== null) {
        safePayload[key] = this.stripSecrets(safePayload[key]);
      }
    }
    return safePayload;
  }

  /**
   * Write an audit log generated by a human user
   */
  async writeHumanLog(actorId: string, entry: AuditLogEntry) {
    const safePayload = this.stripSecrets(entry.payload);
    return prisma.auditLog.create({
      data: {
        actorId,
        actorType: 'HUMAN',
        action: entry.action,
        objectType: entry.objectType ?? null,
        objectId: entry.objectId ?? null,
        jurisdictionId: entry.jurisdictionId ?? null,
        requestId: entry.requestId ?? null,
        payload: safePayload,
        ipAddress: entry.ipAddress ?? null,
        userAgent: entry.userAgent ?? null,
      },
    });
  }

  /**
   * Write an audit log generated by an automated system or background job
   */
  async writeSystemLog(systemName: string, entry: AuditLogEntry) {
    const safePayload = this.stripSecrets(entry.payload);
    return prisma.auditLog.create({
      data: {
        actorId: systemName, // Store system identifier in actorId
        actorType: 'SYSTEM',
        action: entry.action,
        objectType: entry.objectType ?? null,
        objectId: entry.objectId ?? null,
        jurisdictionId: entry.jurisdictionId ?? null,
        requestId: entry.requestId ?? null,
        payload: safePayload,
        ipAddress: entry.ipAddress ?? null,
        userAgent: entry.userAgent ?? null,
      },
    });
  }

  /**
   * Read logs by object (useful for timeline view)
   */
  async getLogsForObject(objectType: string, objectId: string) {
    return prisma.auditLog.findMany({
      where: {
        objectType,
        objectId,
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
  }
}

export const auditService = new AuditService();
